@include('admin.partials.print-document', [
    'title' => 'Sale Invoice',
    'docNo' => $invoice->invoice_no,
    'docDate' => $invoice->billing_date,
    'status' => $invoice->status,
    'party' => $invoice->party,
    'lines' => $invoice->items,
    'billingAddress' => $invoice->billing_address,
    'shippingAddress' => $invoice->shipping_address,
    'subtotal' => $invoice->subtotal,
    'discount' => $invoice->discount_amount,
    'tax' => $invoice->tax_amount,
    'grandTotal' => $invoice->grand_total,
    'totalWeight' => $invoice->total_weight,
    'terms' => $invoice->terms ?: ($defaultTerms?->content ?? ''),
    'company' => $company ?? $invoice->company,
    'bankAccount' => $bankAccount ?? null,
    'accent' => '#2563eb',
    'relatedDocumentNotice' => ($creditNotes ?? collect())->isNotEmpty() ? 'Credit Note(s) issued against this invoice: '.($creditNotes ?? collect())->pluck('credit_note_no')->join(', ').'. Please download the related Credit Note document(s) for complete adjustment details.' : null,
])
