@extends('layouts.admin')
@section('title', 'Issue Cheque')
@section('content')
<form method="POST" action="{{ route('admin.cheques.leaves.store') }}">@csrf<div class="card"><div class="card-header font-weight-bold">Issue Direct Cheque</div><div class="card-body">@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif<div class="alert alert-info">Cheque ab kisi party ke naam par issue nahi hoga. Party payment out ke time select hogi.</div><div class="row"><div class="col-md-5 form-group"><label>Cheque Book *</label><select name="cheque_book_id" id="bookSelect" class="form-control select2" required><option value="">Select book</option>@foreach($books as $book)<option value="{{ $book->id }}">{{ $book->book_no }} | {{ $book->bankAccount?->account_name }} | {{ $book->remaining_leaves }} left</option>@endforeach</select></div><div class="col-md-3 form-group"><label>Cheque Date *</label><input type="date" name="cheque_date" id="chequeDate" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="col-md-4 form-group"><label>Auto Cheque No</label><input id="chequeNo" class="form-control" readonly></div></div><div id="bankInfo" class="alert alert-info" style="display:none"></div><div class="row"><div class="col-md-3 form-group"><label>Amount *</label><input type="number" step="0.01" min="0.01" name="amount" id="amountInput" class="form-control" required></div><div class="col-md-3 form-group"><label>Payee Name</label><input name="payee_name" id="payeeInput" class="form-control" placeholder="Payment out par party se fill hoga"></div><div class="col-md-3 form-group"><label>Payment Validity *</label><select name="validity_months" class="form-control">@for($i=1;$i<=6;$i++)<option value="{{ $i }}" @selected($i===3)>{{ $i }} Month</option>@endfor</select></div><div class="col-md-3 form-group"><label>Memo</label><input name="memo" id="memoInput" class="form-control"></div></div><div class="form-group"><label>Amount In Words</label><input name="amount_words" id="wordsInput" class="form-control"></div><div class="form-group"><label>Description</label><textarea name="description" class="form-control"></textarea></div><div class="mt-4" id="previewBox">@include('admin.cheques.partials.cheque-preview')</div></div><div class="card-footer text-right"><a href="{{ route('admin.cheques.index') }}" class="btn btn-outline-secondary">Cancel</a><button class="btn btn-success">Save Cheque</button></div></div></form>
@push('scripts')
<script>
let selectedBank=null;
function words(n){n=Math.floor(Number(n)||0);if(!n)return '';const a=['','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'],b=['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'];function t(x){return x<20?a[x]:b[Math.floor(x/10)]+(x%10?'-'+a[x%10]:'')}function h(x){return (x>=100?a[Math.floor(x/100)]+' hundred ':'')+(x%100?t(x%100):'')}let p=[],c=Math.floor(n/10000000);n%=10000000,l=Math.floor(n/100000);n%=100000,th=Math.floor(n/1000);n%=1000;if(c)p.push(h(c)+' crore');if(l)p.push(h(l)+' lakh');if(th)p.push(h(th)+' thousand');if(n)p.push(h(n));return p.join(' ').replace(/\b\w/g,m=>m.toUpperCase())}
function refreshPreview(){const b=selectedBank||{};$('.cheque-preview .bank-name').text(b.name||'Bank Account');$('.cheque-preview .bank-sub').first().text(`A/C ${b.account_number||'-'} | IFSC ${b.ifsc_code||'-'}`);$('.cheque-preview .cheque-no .val').text($('#chequeNo').val()||'AUTO');$('.row-date .line').text(($('#chequeDate').val()||'').split('-').reverse().join(' / '));$('.row-pay .line').text($('#payeeInput').val()||'Open cheque');$('.amount-box').text('Rs '+(Number($('#amountInput').val()||0).toFixed(2)));$('#wordsInput').val(words($('#amountInput').val()));$('.row-words .line').text($('#wordsInput').val()||'-');$('.memo-block .line').text($('#memoInput').val()||'-')}
$('#bookSelect').on('change',async function(){if(!this.value)return;const res=await fetch(`{{ url('/admin/cheques/books') }}/${this.value}/info`,{headers:{Accept:'application/json'}});const data=await res.json();selectedBank=data.bank;$('#chequeNo').val(data.next_cheque_no);$('#bankInfo').show().html(`<b>${data.bank.name||'-'}</b> | Account: ${data.bank.account_number||'-'} | IFSC: ${data.bank.ifsc_code||'-'} | Leaves left: ${data.remaining}`);refreshPreview()});
$('#chequeDate,#amountInput,#payeeInput,#memoInput').on('input change',refreshPreview);refreshPreview();
</script>
@endpush
@endsection
