@push('styles')
<style>.trade-shell{background:#fff;border-radius:16px;box-shadow:0 10px 32px rgba(44,24,94,.10);overflow:hidden}.trade-hero{background:linear-gradient(135deg,#4338ca,#2563eb);color:#fff;padding:24px}.trade-hero h2{font-weight:800;margin:0}.trade-section{padding:22px;border-bottom:1px solid #eef2ff}.trade-title{font-size:12px;font-weight:800;color:#2563eb;text-transform:uppercase;letter-spacing:.8px}.total-box{background:#111827;color:#fff;border-radius:14px;padding:18px}.total-row{display:flex;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.08);padding:8px 0}.total-row:last-child{border-bottom:0;font-size:18px;font-weight:800;color:#22c55e}</style>
@endpush
@php $estimate = $estimate ?? new \App\Models\Estimate; $isEdit = $estimate->exists; @endphp
<form method="POST" action="{{ $isEdit ? route('admin.estimates.update', $estimate) : route('admin.estimates.store') }}" enctype="multipart/form-data">@csrf @if($isEdit) @method('PUT') @endif
<div class="trade-shell">
<div class="trade-hero"><h2><i class="fas fa-file-contract mr-2"></i> Estimate / Quotation</h2><div>Create quotation now, convert to sales invoice after approval.</div></div>
<div class="trade-section">
<div class="row">
<div class="col-md-3 form-group"><label>Party</label><select name="party_id" class="form-control select2"><option value="">Walk-in / No Party</option>@foreach($parties as $party)<option value="{{ $party->id }}" @selected((int) old('party_id', $estimate->party_id) === (int) $party->id)>{{ $party->display_name }} | {{ $party->phone }}</option>@endforeach</select></div>
<div class="col-md-2 form-group"><label>Estimate No</label><input name="estimate_no" class="form-control" value="{{ old('estimate_no', $estimate->estimate_no ?: $estimateNo) }}"></div>
<div class="col-md-2 form-group"><label>Date</label><input type="date" name="estimate_date" class="form-control" value="{{ old('estimate_date', $estimate->estimate_date?->toDateString() ?: now()->toDateString()) }}" required></div>
<div class="col-md-2 form-group"><label>Valid Until</label><input type="date" name="valid_until" class="form-control" value="{{ old('valid_until', $estimate->valid_until?->toDateString() ?: now()->addDays(15)->toDateString()) }}"></div>
<div class="col-md-3 form-group"><label>Reference</label><input name="reference_no" class="form-control" value="{{ old('reference_no', $estimate->reference_no) }}"></div>
</div>
<div class="row">
<div class="col-md-3 form-group"><label>Cost Center</label><select name="cost_center_id" class="form-control"><option value="">Select</option>@foreach($costCenters as $cc)<option value="{{ $cc->id }}">{{ $cc->name }}</option>@endforeach</select></div>
<div class="col-md-3 form-group"><label>Sub Cost Center</label><select name="sub_cost_center_id" class="form-control"><option value="">Select</option>@foreach($subCostCenters as $scc)<option value="{{ $scc->id }}">{{ $scc->name }}</option>@endforeach</select></div>
<div class="col-md-3 form-group"><label>Phone</label><input name="phone" class="form-control" value="{{ old('phone', $estimate->phone) }}"></div>
</div>
<div class="row"><div class="col-md-6 form-group"><label>Billing Address</label><textarea name="billing_address" class="form-control">{{ old('billing_address', $estimate->billing_address) }}</textarea></div><div class="col-md-6 form-group"><label>Shipping Address</label><textarea name="shipping_address" class="form-control">{{ old('shipping_address', $estimate->shipping_address) }}</textarea></div></div>
</div>
<div class="trade-section"><div class="trade-title mb-3">Items</div><div class="table-responsive"><table class="table" id="lineTable"><thead><tr><th>Item</th><th>Description</th><th>Qty</th><th>Unit</th><th>Price</th><th>Disc Type</th><th>Disc</th><th>GST Mode</th><th>Tax %</th><th></th></tr></thead><tbody>@foreach($estimate->items ?? [] as $line)<tr><td><select name="item_id[]" class="form-control item-select select2-item" required><option value="">Select</option>@foreach($items as $it)<option value="{{ $it->id }}" data-unit="{{ $it->unit }}" data-price="{{ $it->sale_price }}" data-tax="{{ (float) $it->sale_gst_percent ?: 18 }}" data-max-disc="{{ (float) ($it->max_discount_percent ?? 0) }}" @selected($line->item_id === $it->id)>{{ $it->name }} | Stock {{ $it->current_stock }}@if($it->max_discount_percent) | Max disc {{ $it->max_discount_percent }}%@endif</option>@endforeach</select></td><td><input name="description[]" class="form-control" value="{{ $line->description }}"></td><td><input type="number" step="0.001" name="quantity[]" class="form-control" value="{{ $line->quantity }}" required></td><td><input name="unit[]" class="form-control" value="{{ $line->unit }}"></td><td><input type="number" step="0.01" name="unit_price[]" class="form-control" value="{{ $line->unit_price }}" required></td><td><select name="discount_type[]" class="form-control disc-type"><option value="percent" @selected($line->discount_type === 'percent')>%</option><option value="flat" @selected($line->discount_type === 'flat')>Flat</option></select></td><td><input type="number" step="0.01" name="discount_value[]" class="form-control disc-value" value="{{ $line->discount_value }}"><small class="text-warning disc-warn d-none"></small></td><td><select name="tax_mode[]" class="form-control tax-mode"><option value="with_gst" @selected((float)$line->tax_percent > 0)>With GST</option><option value="without_gst" @selected((float)$line->tax_percent <= 0)>Without GST</option></select></td><td><input type="number" step="0.01" name="tax_percent[]" class="form-control" value="{{ $line->tax_percent }}"></td><td><button type="button" class="btn btn-danger btn-sm remove-row"><i class="fas fa-trash"></i></button></td></tr>@endforeach</tbody></table></div><button type="button" id="addLine" class="btn btn-outline-primary"><i class="fas fa-plus"></i> Add Row</button></div>
<div class="trade-section"><div class="row"><div class="col-md-4 form-group"><label>Overall Discount</label><input type="number" step="0.01" name="discount_amount" class="form-control" value="{{ old('discount_amount', $estimate->exists ? max(0, (float)$estimate->discount_amount - (float)$estimate->items->sum('discount_amount')) : 0) }}"></div><div class="col-md-4 form-group"><label>Attachment</label><input type="file" name="attachment" class="form-control"></div><div class="col-md-4"><div class="total-box"><div class="total-row"><span>Subtotal</span><b id="uiSubtotal">Rs 0.00</b></div><div class="total-row"><span>Discount</span><b id="uiDiscount">Rs 0.00</b></div><div class="total-row"><span>Tax</span><b id="uiTax">Rs 0.00</b></div><div class="total-row"><span>Total</span><b id="uiTotal">Rs 0.00</b></div></div></div><div class="col-md-6 form-group"><label>Notes</label><textarea name="notes" class="form-control">{{ old('notes', $estimate->notes) }}</textarea></div><div class="col-md-6 form-group"><label>Terms</label><textarea name="terms" class="form-control">{{ old('terms', $estimate->terms) }}</textarea></div></div>@include('admin.partials.entry-visibility')</div>
<div class="p-4 text-right"><button class="btn btn-primary btn-lg"><i class="fas fa-save mr-1"></i> Save Estimate</button></div>
</div></form>
<template id="lineTpl"><tr><td><select name="item_id[]" class="form-control item-select select2-item" required><option value="">Select</option>@foreach($items as $it)<option value="{{ $it->id }}" data-unit="{{ $it->unit }}" data-price="{{ $it->sale_price }}" data-tax="{{ (float) $it->sale_gst_percent ?: 18 }}" data-max-disc="{{ (float) ($it->max_discount_percent ?? 0) }}">{{ $it->name }} | Stock {{ $it->current_stock }}@if($it->max_discount_percent) | Max disc {{ $it->max_discount_percent }}%@endif</option>@endforeach</select></td><td><input name="description[]" class="form-control"></td><td><input type="number" step="0.001" name="quantity[]" class="form-control" value="1" required></td><td><input name="unit[]" class="form-control"></td><td><input type="number" step="0.01" name="unit_price[]" class="form-control" required></td><td><select name="discount_type[]" class="form-control disc-type"><option value="percent">%</option><option value="flat">Flat</option></select></td><td><input type="number" step="0.01" name="discount_value[]" class="form-control disc-value" value="0"><small class="text-warning disc-warn d-none"></small></td><td><select name="tax_mode[]" class="form-control tax-mode"><option value="with_gst">With GST</option><option value="without_gst">Without GST</option></select></td><td><input type="number" step="0.01" name="tax_percent[]" class="form-control" value="18"></td><td><button type="button" class="btn btn-danger btn-sm remove-row"><i class="fas fa-trash"></i></button></td></tr></template>
@push('scripts')<script>function money(n){return 'Rs '+(Number(n)||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}function initItemSelect(scope){$(scope).find('.select2-item').each(function(){let $select=$(this);if($select.hasClass('select2-hidden-accessible'))$select.select2('destroy');$select.select2({width:'100%',placeholder:'Search item',allowClear:true,dropdownAutoWidth:true})})}function enforce(r){let o=r.find('.item-select :selected'),max=+o.data('max-disc')||0,q=+r.find('[name="quantity[]"]').val()||0,p=+r.find('[name="unit_price[]"]').val()||0,b=q*p,d=+r.find('.disc-value').val()||0,dt=r.find('.disc-type').val(),pct=dt==='flat'&&b>0?d/b*100:d,w=r.find('.disc-warn');if(max>0&&pct>max){if(dt==='flat')r.find('.disc-value').val((b*max/100).toFixed(2));else r.find('.disc-value').val(max.toFixed(2));w.removeClass('d-none').text('Max '+max+'% discount allowed');return true}w.addClass('d-none').text('');return false}function calc(){let sub=0,tax=0,disc=0;$('#lineTable tbody tr').each(function(){let r=$(this);enforce(r);let q=+r.find('[name="quantity[]"]').val()||0,p=+r.find('[name="unit_price[]"]').val()||0,d=+r.find('[name="discount_value[]"]').val()||0,dt=r.find('[name="discount_type[]"]').val(),tx=r.find('[name="tax_mode[]"]').val()==='without_gst'?0:(+r.find('[name="tax_percent[]"]').val()||0),b=q*p,da=dt==='flat'?d:b*d/100,g=Math.max(0,b-da),ta=tx>0?g*tx/(100+tx):0;sub+=Math.max(0,g-ta);tax+=ta;disc+=da});let od=+$('[name="discount_amount"]').val()||0;$('#uiSubtotal').text(money(sub));$('#uiDiscount').text(money(disc+od));$('#uiTax').text(money(tax));$('#uiTotal').text(money(Math.max(0,sub+tax-od)))}function addLine(){let $row=$($('#lineTpl').html());$('#lineTable tbody').append($row);initItemSelect($row);calc()}$('#addLine').click(addLine);$(document).on('input change','#lineTable input,#lineTable select,[name="discount_amount"]',calc);$(document).on('click','.remove-row',function(){let $row=$(this).closest('tr');let $select=$row.find('.select2-item');if($select.hasClass('select2-hidden-accessible'))$select.select2('destroy');$row.remove();calc()});$(document).on('change','.item-select',function(){let o=$(this).find(':selected'),r=$(this).closest('tr');r.find('[name="unit[]"]').val(o.data('unit'));r.find('[name="unit_price[]"]').val(o.data('price'));if(r.find('[name="tax_mode[]"]').val()!=='without_gst')r.find('[name="tax_percent[]"]').val(o.data('tax')||18);r.find('.disc-value').val(0);calc()});$(document).on('change','.tax-mode',function(){let r=$(this).closest('tr');if(this.value==='without_gst')r.find('[name="tax_percent[]"]').val(0);else r.find('[name="tax_percent[]"]').val(r.find('.item-select :selected').data('tax')||18);calc()});if(!$('#lineTable tbody tr').length){addLine()}else{initItemSelect($('#lineTable'));calc()}</script>@endpush
