@php
    $editing = isset($creditNote) && $creditNote;
    $existing = $editing ? $creditNote->items->mapWithKeys(fn($row) => [$row->sales_invoice_item_id => ['quantity'=>(float)$row->quantity,'selected_units'=>$row->selected_units ?? []]]) : collect();
@endphp
@push('styles')<style>
.cn-shell{background:#fff;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;box-shadow:0 10px 30px rgba(15,23,42,.07)}.cn-head{background:#172033;color:#fff;padding:22px 25px}.cn-head h3{font-weight:800;margin:0}.invoice-facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;background:#f8fafc;border:1px solid #e2e8f0;padding:14px;margin-bottom:18px}.fact small{display:block;color:#64748b;text-transform:uppercase;font-weight:700;font-size:10px}.cn-table th{font-size:11px;text-transform:uppercase;color:#475569;background:#f8fafc}.cn-table td{vertical-align:middle}.cn-total{background:#172033;color:#fff;padding:18px 22px}.serial-chip{display:inline-block;background:#ecfdf5;color:#047857;border:1px solid #a7f3d0;padding:3px 7px;margin:2px;font-size:11px}.serial-option{display:block;border:1px solid #e2e8f0;padding:10px;margin-bottom:8px;cursor:pointer}.serial-option.selected{border-color:#2563eb;background:#eff6ff}@media(max-width:767px){.invoice-facts{grid-template-columns:1fr 1fr}.cn-head{padding:18px}.cn-table{min-width:1050px}}
</style>@endpush
<form method="POST" action="{{ $formAction }}" id="creditNoteForm">@csrf @if($formMethod==='PUT')@method('PUT')@endif
<input type="hidden" name="allow_without_return" id="allowWithoutReturn" value="{{ old('allow_without_return',0) }}">
<div class="cn-shell">
    <div class="cn-head d-flex justify-content-between align-items-center"><div><h3><i class="fas fa-file-invoice-dollar mr-2"></i>{{ $editing ? 'Edit' : 'New' }} Credit Note</h3><small style="opacity:.72">Select invoice items and exact sold serial numbers.</small></div><a href="{{ route('admin.credit-notes.index') }}" class="btn btn-outline-light btn-sm">Back</a></div>
    <div class="p-4">
        @if(isset($errors) && $errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
        <div class="row">
            <div class="col-md-4 form-group"><label>Sales Invoice</label><select name="sales_invoice_id" id="sourceInvoice" class="form-control select2" required><option value="">Select invoice</option>@foreach($invoices as $invoice)<option value="{{ $invoice->id }}" @selected((string)old('sales_invoice_id',optional($creditNote)->sales_invoice_id ?? '')===(string)$invoice->id)>{{ $invoice->invoice_no }} | {{ $invoice->party?->display_name ?: 'Cash' }} | Rs {{ number_format((float)$invoice->grand_total,2) }}</option>@endforeach</select></div>
            <div class="col-md-3 form-group"><label>Credit Note No.</label><input name="credit_note_no" class="form-control" value="{{ old('credit_note_no',$creditNoteNo) }}"></div>
            <div class="col-md-2 form-group"><label>Date</label><input type="date" name="credit_note_date" class="form-control" value="{{ old('credit_note_date',optional(optional($creditNote)->credit_note_date)->toDateString() ?? now()->toDateString()) }}" required></div>
            <div class="col-md-3 form-group"><label>Reason</label><input name="reason" class="form-control" value="{{ old('reason',optional($creditNote)->reason ?? '') }}"></div>
        </div>
        <div id="invoiceFacts"></div><div id="creditLines"><div class="text-center text-muted py-5">Select a sales invoice to view items.</div></div>
        @include('admin.partials.entry-visibility')
    </div>
    <div class="cn-total d-flex flex-wrap justify-content-end" style="gap:28px"><div><small>Subtotal</small><div class="h5 mb-0" id="subtotalText">Rs 0.00</div></div><div><small>Tax</small><div class="h5 mb-0" id="taxText">Rs 0.00</div></div><div><small>Credit Note Total</small><div class="h4 mb-0" id="totalText">Rs 0.00</div></div><button class="btn btn-primary px-4 ml-3"><i class="fas fa-save mr-1"></i>Save Credit Note</button></div>
</div></form>
<div class="modal fade" id="serialModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header bg-dark text-white"><h5 class="modal-title">Select sold serials</h5><button class="close text-white" data-dismiss="modal">&times;</button></div><div class="modal-body"><div id="serialHelp" class="mb-3"></div><div id="serialOptions"></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button><button type="button" class="btn btn-primary" id="useSerials">Use selected serials</button></div></div></div></div>
<div class="modal fade" id="returnWarningModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header bg-warning"><h5 class="modal-title"><i class="fas fa-exclamation-triangle mr-2"></i>Sales Return Pending</h5><button class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><p class="mb-2">Selected items/serial numbers ka Sales Return abhi receive nahi hua hai.</p><div class="alert alert-light border mb-0"><b>Stock impact:</b> Credit Note save ho jayega, lekin bina Sales Return ke ye items stock me add nahi honge. Pehle Sales Return lena recommended hai.</div></div><div class="modal-footer"><button class="btn btn-outline-secondary" data-dismiss="modal">Go Back</button><button type="button" class="btn btn-warning" id="confirmWithoutReturn">Save without Sales Return</button></div></div></div></div>
@push('scripts')<script>
const CN_INVOICES=@json($invoiceData),CN_EXISTING=@json($existing);let activeIndex=null,activeSelection=[];
const money=v=>'Rs '+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const unitLabel=u=>u.serial_no||u.sku||u.vts_sim||u.batch_no||u.key||'Unit';
function selected(i){try{return JSON.parse($(`.cn-units[data-index="${i}"]`).val()||'[]')}catch(e){return[]}}
function setSelected(i,units){$(`.cn-units[data-index="${i}"]`).val(JSON.stringify(units));$(`.serial-summary[data-index="${i}"]`).html(units.length?units.map(u=>`<span class="serial-chip"><i class="fas fa-barcode mr-1"></i>${unitLabel(u)}</span>`).join(''):'<span class="text-muted small">No serial selected</span>');$(`.serial-count[data-index="${i}"]`).text(units.length)}
function calculate(){let subtotal=0,tax=0,total=0;$('.line-check:checked').each(function(){const i=$(this).data('index'),row=$(`.cn-row[data-index="${i}"]`),line=row.data('line'),qty=Number(row.find('.cn-qty').val()||0),ratio=Number(line.sold_qty)>0?qty/Number(line.sold_qty):0,lineTotal=Number(line.line_total||0)*ratio,lineTax=Number(line.tax_amount||0)*ratio;subtotal+=lineTotal-lineTax;tax+=lineTax;total+=lineTotal;row.find('.line-total').text(money(lineTotal))});$('#subtotalText').text(money(subtotal));$('#taxText').text(money(tax));$('#totalText').text(money(total))}
function render(invoice){if(!invoice){$('#invoiceFacts').empty();$('#creditLines').html('<div class="text-center text-muted py-5">Select a sales invoice to view items.</div>');calculate();return}$('#invoiceFacts').html(`<div class="invoice-facts"><div class="fact"><small>Invoice</small><b>${invoice.invoice_no}</b></div><div class="fact"><small>Date</small><b>${invoice.date||'-'}</b></div><div class="fact"><small>Party</small><b>${invoice.party}</b></div><div class="fact"><small>Invoice Total</small><b>${money(invoice.grand_total)}</b></div></div>`);const rows=invoice.lines.map((line,i)=>{const old=CN_EXISTING[line.id]||null,checked=!!old;return `<tr class="cn-row" data-index="${i}"><td><input type="checkbox" class="line-check" data-index="${i}" ${checked?'checked':''}></td><td><b>${line.item}</b><br><small class="text-muted">SKU: ${line.sku}</small><input type="hidden" name="line_id[]" value="${line.id}" ${checked?'':'disabled'}><input type="hidden" name="selected_units[]" class="cn-units" data-index="${i}" value='[]' ${checked?'':'disabled'}></td><td>${line.sold_qty} ${line.unit||''}</td><td>${line.returned_qty} ${line.unit||''}</td><td style="width:130px"><input type="number" name="quantity[]" class="form-control cn-qty" min="0" max="${line.available_qty}" step="${line.sold_units.length?'1':'0.001'}" value="${old?old.quantity:line.available_qty}" ${checked?'':'disabled'}><small class="text-muted">Max ${line.available_qty}</small></td><td>${line.sold_units.length?`<button type="button" class="btn btn-outline-primary btn-sm choose-serials" data-index="${i}" ${checked?'':'disabled'}><i class="fas fa-barcode"></i> <span class="serial-count" data-index="${i}">0</span></button><div class="serial-summary mt-1" data-index="${i}"></div>`:'<span class="text-muted">N/A</span>'}</td><td>${money(line.unit_price)}</td><td>${Number(line.tax_percent).toFixed(2)}%</td><td><b class="line-total">Rs 0.00</b></td></tr>`}).join('');$('#creditLines').html(`<div class="table-responsive"><table class="table cn-table"><thead><tr><th></th><th>Item / SKU</th><th>Sold</th><th>Returned</th><th>Credit Qty</th><th>Serials</th><th>Price</th><th>Tax</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table></div>`);invoice.lines.forEach((line,i)=>{$(`.cn-row[data-index="${i}"]`).data('line',line);if(CN_EXISTING[line.id])setSelected(i,CN_EXISTING[line.id].selected_units||[])});calculate()}
$('#sourceInvoice').on('change',function(){render(CN_INVOICES[this.value])});
$(document).on('change','.line-check',function(){const i=$(this).data('index'),row=$(`.cn-row[data-index="${i}"]`),enabled=this.checked;row.find('input[name="line_id[]"],input[name="quantity[]"],input[name="selected_units[]"],.choose-serials').prop('disabled',!enabled);if(!enabled)setSelected(i,[]);calculate()});
$(document).on('input','.cn-qty',function(){const row=$(this).closest('.cn-row'),line=row.data('line'),max=Number(line.available_qty),i=row.data('index');if(Number(this.value)>max)this.value=max;if(line.sold_units.length&&Number(this.value)%1!==0)this.value=Math.floor(Number(this.value)||0);setSelected(i,selected(i).slice(0,Number(this.value)||0));calculate()});
$(document).on('click','.choose-serials',function(){activeIndex=$(this).data('index');const line=$(`.cn-row[data-index="${activeIndex}"]`).data('line'),keys=selected(activeIndex).map(u=>u.key);activeSelection=selected(activeIndex);$('#serialHelp').html(`<b>${line.item}</b><br><span class="text-muted">Credit quantity ke barabar serial select karein. Green badge ka matlab Sales Return received hai.</span>`);$('#serialOptions').html(line.sold_units.map(u=>{const used=line.credited_unit_keys.includes(u.key);return `<label class="serial-option ${keys.includes(u.key)?'selected':''} ${used?'text-muted':''}"><input type="checkbox" class="serial-check mr-2" data-key="${u.key}" ${keys.includes(u.key)?'checked':''} ${used?'disabled':''}> <b>${unitLabel(u)}</b> ${used?'<span class="badge badge-secondary float-right">Already credited</span>':(line.returned_unit_keys.includes(u.key)?'<span class="badge badge-success float-right">Return received</span>':'<span class="badge badge-warning float-right">Return pending</span>')}</label>`}).join(''));$('#serialModal').modal('show')});
$(document).on('change','.serial-check',function(){const line=$(`.cn-row[data-index="${activeIndex}"]`).data('line'),unit=line.sold_units.find(u=>u.key===$(this).data('key')),required=Number($(`.cn-row[data-index="${activeIndex}"] .cn-qty`).val()||0);if(this.checked){if(activeSelection.length>=required){this.checked=false;alert(`Sirf ${required} serial select kar sakte hain.`);return}activeSelection.push(unit);$(this).closest('label').addClass('selected')}else{activeSelection=activeSelection.filter(u=>u.key!==$(this).data('key'));$(this).closest('label').removeClass('selected')}});
$('#useSerials').on('click',function(){const required=Number($(`.cn-row[data-index="${activeIndex}"] .cn-qty`).val()||0);if(activeSelection.length!==required){alert(`Exactly ${required} serial select karein.`);return}setSelected(activeIndex,activeSelection);$('#serialModal').modal('hide')});
function hasReturnGap(){let gap=false;$('.line-check:checked').each(function(){const i=$(this).data('index'),row=$(`.cn-row[data-index="${i}"]`),line=row.data('line'),qty=Number(row.find('.cn-qty').val()||0);if(line.sold_units.length){if(selected(i).some(u=>!line.returned_unit_keys.includes(u.key)))gap=true}else if(qty>Number(line.returned_qty))gap=true});return gap}
$('#creditNoteForm').on('submit',function(e){if($('#allowWithoutReturn').val()==='1')return;let serialInvalid=false;$('.line-check:checked').each(function(){const i=$(this).data('index'),row=$(`.cn-row[data-index="${i}"]`),line=row.data('line'),qty=Number(row.find('.cn-qty').val()||0);if(line.sold_units.length&&selected(i).length!==qty)serialInvalid=true});if(serialInvalid){e.preventDefault();alert('Selected serial item ki quantity ke barabar exact serial numbers select karein.');return}if(hasReturnGap()){e.preventDefault();$('#returnWarningModal').modal('show')}});$('#confirmWithoutReturn').on('click',function(){$('#allowWithoutReturn').val('1');$('#returnWarningModal').modal('hide');$('#creditNoteForm')[0].submit()});
if($('#sourceInvoice').val())$('#sourceInvoice').trigger('change');
</script>@endpush
