@extends('layouts.admin')
@section('title','Credit Note')
@section('content')
<div class="card border-0 shadow-sm">
    <div class="card-header d-flex justify-content-between align-items-center"><div><h3 class="card-title m-0">Credit Note {{ $creditNote->credit_note_no }}</h3><small class="text-muted">Against Sales Invoice {{ $creditNote->invoice?->invoice_no }}</small></div><div>@can('credit_notes.print')<a href="{{ route('admin.credit-notes.print',$creditNote) }}" target="_blank" class="btn btn-secondary btn-sm"><i class="fas fa-print mr-1"></i>Print</a>@endcan @can('credit_notes.edit')<a href="{{ route('admin.credit-notes.edit',$creditNote) }}" class="btn btn-warning btn-sm"><i class="fas fa-edit mr-1"></i>Edit</a>@endcan <a href="{{ route('admin.credit-notes.index') }}" class="btn btn-outline-secondary btn-sm">Back</a></div></div>
    <div class="card-body">
        <div class="row mb-4"><div class="col-md-3"><small class="text-muted">Party</small><div class="font-weight-bold">{{ $creditNote->party?->display_name ?: 'Cash' }}</div></div><div class="col-md-2"><small class="text-muted">Date</small><div class="font-weight-bold">{{ $creditNote->credit_note_date?->format('d M Y') }}</div></div><div class="col-md-3"><small class="text-muted">Against Invoice</small><div><a href="{{ route('admin.sales.show',$creditNote->invoice) }}"><b>{{ $creditNote->invoice?->invoice_no }}</b></a></div></div><div class="col-md-2"><small class="text-muted">Total Credit</small><div class="h5">Rs {{ number_format((float)$creditNote->grand_total,2) }}</div></div><div class="col-md-2"><small class="text-muted">Stock Return</small><div>@if($creditNote->hasCompleteSalesReturn())<span class="badge badge-success">Received</span>@else<span class="badge badge-warning">Pending</span>@endif</div></div></div>
        @if(!$creditNote->hasCompleteSalesReturn())<div class="alert alert-warning"><b>Sales Return pending:</b> Credit Note pass ho gaya hai, lekin selected items Sales Return ke bina stock me add nahi hue hain.</div>@endif
        <div class="table-responsive"><table class="table table-hover"><thead><tr><th>Item / SKU</th><th>Qty</th><th>Serial Details</th><th>Price</th><th>Tax</th><th>Total</th></tr></thead><tbody>@foreach($creditNote->items as $line)<tr><td><b>{{ $line->item?->name }}</b><br><small class="text-muted">SKU: {{ $line->item?->item_code ?: '-' }}</small></td><td>{{ number_format((float)$line->quantity,3) }} {{ $line->unit }}</td><td>@forelse(($line->selected_units ?? []) as $unit)<span class="badge badge-info mr-1 mb-1">{{ $unit['serial_no'] ?? $unit['sku'] ?? $unit['vts_sim'] ?? $unit['key'] ?? 'Unit' }}</span>@empty<span class="text-muted">Not applicable</span>@endforelse</td><td>Rs {{ number_format((float)$line->unit_price,2) }}</td><td>Rs {{ number_format((float)$line->tax_amount,2) }}</td><td><b>Rs {{ number_format((float)$line->line_total,2) }}</b></td></tr>@endforeach</tbody><tfoot><tr><th colspan="5" class="text-right">Subtotal</th><th>Rs {{ number_format((float)$creditNote->subtotal,2) }}</th></tr><tr><th colspan="5" class="text-right">Tax</th><th>Rs {{ number_format((float)$creditNote->tax_amount,2) }}</th></tr><tr><th colspan="5" class="text-right">Credit Note Total</th><th>Rs {{ number_format((float)$creditNote->grand_total,2) }}</th></tr></tfoot></table></div>
        @if($creditNote->reason)<div class="mt-3"><small class="text-muted">Reason</small><p>{{ $creditNote->reason }}</p></div>@endif
    </div>
    @can('credit_notes.delete')<div class="card-footer text-right"><form method="POST" action="{{ route('admin.credit-notes.destroy',$creditNote) }}" class="d-inline" onsubmit="return confirm('Delete this Credit Note?')">@csrf @method('DELETE')<button class="btn btn-outline-danger btn-sm"><i class="fas fa-trash mr-1"></i>Delete</button></form></div>@endcan
</div>
@endsection
